encrypt:
  key: "your-very-strong-secret-key-at-least-12-chars"  # Must be at least 12 characters long

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dxdaniel/sc-demo.git
          default-label: main

server:
  port: 8888
