encrypt:
  keyStore:
    location: keystore.jks
    password: letmein
    alias: mytestkey
    secret: changeme

example:
  message: "Hello from Spring Cloud Config!"
  value: 42
  environment: "Development"

myapp:
  secretKey: '{cipher}AQA6EN7aXNXrBFVXsXq4HFa1gxHPZp9V2m6WXXuQWL...'
  database:
    password: '{cipher}AQA6EN7aXNXrBFVXsXq3HFa1gxHPZp9V2m6WXXuQWL...'

spring:
  application:
    name: my-values
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dxdaniel/sc-demo.git
          default-label: main

server:
  port: 8888
